### ISSUE TITLE
Ask before overwriting output file

### ISSUE THREAD

**Issue by fluxsauce** [flipstewart/gifhorse#4]
Because that's just polite.

**Comment by flipstewart** [comment]
Eh, this isn't a feature of imagemagick or ffmpeg, and it would get the in the way of quickly experimenting with arguments.

**Comment by fluxsauce** [comment]
![image](https://cloud.githubusercontent.com/assets/976391/9044351/eb7ac2e0-39d0-11e5-8522-b4f4810f01e4.png)
